name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Github clone
        run: echo "test"
      - name: Github clone
        run: git clone https://${{ secrets.GITHUB_TOKEN }}@$github.com/Journaudb/fblog.git
      - name: Build
        run: cargo build --verbose
        working-directory: ./fblog
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./fblog
