name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          repository: Journaudb/fblog.git
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Build
        run: cargo build --verbose
        working-directory: ./fblog
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./fblog
